spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/ffs
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create
        database-platform:
        properties:
            hibernate:
                show_sql: true
                format_sql: true